name: Port and Build Lost Cities
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Execute Port Script
        run: |
          chmod +x ./port_to_fabric.sh
          ./port_to_fabric.sh

      - name: Upload Mod Jar
        uses: actions/upload-artifact@v4
        with:
          name: LostCities-Fabric-Build
          path: build/libs/*.jar

